name: Generate Datas

on:
  schedule:
    - cron: "*/12 * * * *"  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Update and Deploy
    runs-on: ubuntu-latest

    steps:
      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: zellyirigon
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Ensure 'dist' directory exists
      - name: Create Build Directory
        run: mkdir -p dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


